//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спр тип транс ср.
    /// </summary>
    // *** Start programmer edit section *** (СпрТипТрансСр CustomAttributes)

    // *** End programmer edit section *** (СпрТипТрансСр CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник типы транспортного средства")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрТипТрансСрE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "Описание as \'Описание\'",
            "ВместВКубМ as \'Вместимость в кубических метрах\'"})]
    [View("СпрТипТрансСрL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "Описание as \'Описание\'",
            "ВместВКубМ as \'Вместимость в кубических метрах\'"})]
    public class СпрТипТрансСр : ICSSoft.STORMNET.DataObject
    {
        
        private string fОписание;
        
        private float fВместВКубМ;
        
        private string fНаименование;
        
        private int fКод;
        
        // *** Start programmer edit section *** (СпрТипТрансСр CustomMembers)

        // *** End programmer edit section *** (СпрТипТрансСр CustomMembers)

        
        /// <summary>
        /// ВместВКубМ.
        /// </summary>
        // *** Start programmer edit section *** (СпрТипТрансСр.ВместВКубМ CustomAttributes)

        // *** End programmer edit section *** (СпрТипТрансСр.ВместВКубМ CustomAttributes)
        public virtual float ВместВКубМ
        {
            get
            {
                // *** Start programmer edit section *** (СпрТипТрансСр.ВместВКубМ Get start)

                // *** End programmer edit section *** (СпрТипТрансСр.ВместВКубМ Get start)
                float result = this.fВместВКубМ;
                // *** Start programmer edit section *** (СпрТипТрансСр.ВместВКубМ Get end)

                // *** End programmer edit section *** (СпрТипТрансСр.ВместВКубМ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрТипТрансСр.ВместВКубМ Set start)

                // *** End programmer edit section *** (СпрТипТрансСр.ВместВКубМ Set start)
                this.fВместВКубМ = value;
                // *** Start programmer edit section *** (СпрТипТрансСр.ВместВКубМ Set end)

                // *** End programmer edit section *** (СпрТипТрансСр.ВместВКубМ Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (СпрТипТрансСр.Код CustomAttributes)

        // *** End programmer edit section *** (СпрТипТрансСр.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (СпрТипТрансСр.Код Get start)

                // *** End programmer edit section *** (СпрТипТрансСр.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (СпрТипТрансСр.Код Get end)

                // *** End programmer edit section *** (СпрТипТрансСр.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрТипТрансСр.Код Set start)

                // *** End programmer edit section *** (СпрТипТрансСр.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (СпрТипТрансСр.Код Set end)

                // *** End programmer edit section *** (СпрТипТрансСр.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СпрТипТрансСр.Наименование CustomAttributes)

        // *** End programmer edit section *** (СпрТипТрансСр.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СпрТипТрансСр.Наименование Get start)

                // *** End programmer edit section *** (СпрТипТрансСр.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СпрТипТрансСр.Наименование Get end)

                // *** End programmer edit section *** (СпрТипТрансСр.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрТипТрансСр.Наименование Set start)

                // *** End programmer edit section *** (СпрТипТрансСр.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СпрТипТрансСр.Наименование Set end)

                // *** End programmer edit section *** (СпрТипТрансСр.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (СпрТипТрансСр.Описание CustomAttributes)

        // *** End programmer edit section *** (СпрТипТрансСр.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (СпрТипТрансСр.Описание Get start)

                // *** End programmer edit section *** (СпрТипТрансСр.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (СпрТипТрансСр.Описание Get end)

                // *** End programmer edit section *** (СпрТипТрансСр.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрТипТрансСр.Описание Set start)

                // *** End programmer edit section *** (СпрТипТрансСр.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (СпрТипТрансСр.Описание Set end)

                // *** End programmer edit section *** (СпрТипТрансСр.Описание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрТипТрансСрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрТипТрансСрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрТипТрансСрE", typeof(IIS.Prilozhenie.СпрТипТрансСр));
                }
            }
            
            /// <summary>
            /// "СпрТипТрансСрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрТипТрансСрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрТипТрансСрL", typeof(IIS.Prilozhenie.СпрТипТрансСр));
                }
            }
        }
    }
}
