//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спр ед измер.
    /// </summary>
    // *** Start programmer edit section *** (СпрЕдИзмер CustomAttributes)

    // *** End programmer edit section *** (СпрЕдИзмер CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник единицы измерения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрЕдИзмерE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    [View("СпрЕдИзмерL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    public class СпрЕдИзмер : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (СпрЕдИзмер CustomMembers)

        // *** End programmer edit section *** (СпрЕдИзмер CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (СпрЕдИзмер.Код CustomAttributes)

        // *** End programmer edit section *** (СпрЕдИзмер.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (СпрЕдИзмер.Код Get start)

                // *** End programmer edit section *** (СпрЕдИзмер.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (СпрЕдИзмер.Код Get end)

                // *** End programmer edit section *** (СпрЕдИзмер.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрЕдИзмер.Код Set start)

                // *** End programmer edit section *** (СпрЕдИзмер.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (СпрЕдИзмер.Код Set end)

                // *** End programmer edit section *** (СпрЕдИзмер.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СпрЕдИзмер.Наименование CustomAttributes)

        // *** End programmer edit section *** (СпрЕдИзмер.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СпрЕдИзмер.Наименование Get start)

                // *** End programmer edit section *** (СпрЕдИзмер.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СпрЕдИзмер.Наименование Get end)

                // *** End programmer edit section *** (СпрЕдИзмер.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрЕдИзмер.Наименование Set start)

                // *** End programmer edit section *** (СпрЕдИзмер.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СпрЕдИзмер.Наименование Set end)

                // *** End programmer edit section *** (СпрЕдИзмер.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрЕдИзмерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрЕдИзмерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрЕдИзмерE", typeof(IIS.Prilozhenie.СпрЕдИзмер));
                }
            }
            
            /// <summary>
            /// "СпрЕдИзмерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрЕдИзмерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрЕдИзмерL", typeof(IIS.Prilozhenie.СпрЕдИзмер));
                }
            }
        }
    }
}
