//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спр объект стр.
    /// </summary>
    // *** Start programmer edit section *** (СпрОбъектСтр CustomAttributes)

    // *** End programmer edit section *** (СпрОбъектСтр CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник объекты строительства")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрОбъектСтрE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    [View("СпрОбъектСтрL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    public class СпрОбъектСтр : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private int fКод;
        
        // *** Start programmer edit section *** (СпрОбъектСтр CustomMembers)

        // *** End programmer edit section *** (СпрОбъектСтр CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (СпрОбъектСтр.Код CustomAttributes)

        // *** End programmer edit section *** (СпрОбъектСтр.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (СпрОбъектСтр.Код Get start)

                // *** End programmer edit section *** (СпрОбъектСтр.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (СпрОбъектСтр.Код Get end)

                // *** End programmer edit section *** (СпрОбъектСтр.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрОбъектСтр.Код Set start)

                // *** End programmer edit section *** (СпрОбъектСтр.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (СпрОбъектСтр.Код Set end)

                // *** End programmer edit section *** (СпрОбъектСтр.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СпрОбъектСтр.Наименование CustomAttributes)

        // *** End programmer edit section *** (СпрОбъектСтр.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СпрОбъектСтр.Наименование Get start)

                // *** End programmer edit section *** (СпрОбъектСтр.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СпрОбъектСтр.Наименование Get end)

                // *** End programmer edit section *** (СпрОбъектСтр.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрОбъектСтр.Наименование Set start)

                // *** End programmer edit section *** (СпрОбъектСтр.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СпрОбъектСтр.Наименование Set end)

                // *** End programmer edit section *** (СпрОбъектСтр.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрОбъектСтрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрОбъектСтрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрОбъектСтрE", typeof(IIS.Prilozhenie.СпрОбъектСтр));
                }
            }
            
            /// <summary>
            /// "СпрОбъектСтрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрОбъектСтрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрОбъектСтрL", typeof(IIS.Prilozhenie.СпрОбъектСтр));
                }
            }
        }
    }
}
